In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
from datetime import datetime
start = datetime.now()

# Numpy

## Numpy Arrays

Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

In [3]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
# start, end ,steps
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [7]:
# start, end, counts
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
# random
np.random.rand(2)

array([0.13064489, 0.69237437])

In [10]:
# random
np.random.rand(3,3)

array([[1.92168276e-04, 3.59183798e-01, 4.46249305e-01],
       [1.34643200e-01, 1.36239475e-01, 2.41595151e-01],
       [8.63861944e-01, 3.18586994e-02, 1.41179516e-01]])

In [11]:
# random normal
np.random.randn(3,3)

array([[-1.39913511, -0.37446864, -0.62134583],
       [-0.30768707,  1.03265037,  1.39679364],
       [-0.06139465,  0.9955354 ,  0.4422452 ]])

In [50]:
# int, start, end, shape
np.random.randint(1,100,(2,2))

array([[44, 32],
       [ 4, 90]])

In [13]:
# reshape
arr = np.arange(9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
# max
arr_rand = np.random.randint(0,50,10)
print (arr_rand)
print (arr_rand.max())
print (arr_rand.argmax())
print (arr_rand.dtype)

[ 7 30 46  7 49 35 28  2 41 11]
49
4
int32


## Numpy Indexing & Seelction

### 1D array

In [58]:
arr = np.arange(0,11)
print (arr)
print (arr[8])
print (arr[1:5])

[ 0  1  2  3  4  5  6  7  8  9 10]
8
[1 2 3 4]


In [59]:
# altering values
print (arr[0:5])
arr[0:5]=100
print (arr[0:5])

[0 1 2 3 4]
[100 100 100 100 100]


In [17]:
arr = np.arange(0,11)
print (f"Original Array: {arr}")
slice_of_arr = arr[0:6]
print (f"Slice of Array: {slice_of_arr}")
slice_of_arr[:]=99
print (f"Altered Array: {slice_of_arr}")
print (f"Original Array: {arr}")
print ('Original array changed! Use .copy to avoid this problem ')

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10]
Slice of Array: [0 1 2 3 4 5]
Altered Array: [99 99 99 99 99 99]
Original Array: [99 99 99 99 99 99  6  7  8  9 10]
Original array changed! Use .copy to avoid this problem 


In [18]:
arr = np.arange(0,11)
print (f"Original Array: {arr}")
slice_of_arr = arr[0:6].copy()
print (f"Slice of Array: {slice_of_arr}")
slice_of_arr[:]=99
print (f"Altered Array: {slice_of_arr}")
print (f"Original Array: {arr}")
print ('Original array remains!')

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10]
Slice of Array: [0 1 2 3 4 5]
Altered Array: [99 99 99 99 99 99]
Original Array: [ 0  1  2  3  4  5  6  7  8  9 10]
Original array remains!


### 2D array

In [19]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
print ("Original Array:")
print (arr_2d)
print ("2nd Row:")
print (arr_2d[1])
print ("2nd Row First Elements:")
print (arr_2d[1,0])
print ("End at 2nd row, start at 1st column:")
print (arr_2d[:2,1:])
print ("Last row all columns:")
print (arr_2d[2,:])

Original Array:
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
2nd Row:
[20 25 30]
2nd Row First Elements:
20
End at 2nd row, start at 1st column:
[[10 15]
 [25 30]]
Last row all columns:
[35 40 45]


In [20]:
# fancy indexing
arr_2d = np.zeros((10,10))
arr_length = arr_2d.shape[1]
for i in range(arr_length):
    arr_2d[i] = i
print (arr_2d)
print("")
print (arr_2d[[2,4,6,8]])
print("")
print(arr_2d[[6,4,2,7]])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [9. 9. 9. 9. 9. 9. 9. 9. 9. 9.]]

[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]]

[[6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]]


### Selection

In [21]:
arr = np.arange(1,11)
print(arr)
print(arr > 4)
print(arr[arr > 4])

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False  True  True  True  True  True  True]
[ 5  6  7  8  9 10]


## Numpy Operations

In [22]:
arr = np.arange(0,5)
print(arr)

[0 1 2 3 4]


In [23]:
print(arr * arr)
print(arr**3)
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[ 0  1  4  9 16]
[ 0  1  8 27 64]
[0.         1.         1.41421356 1.73205081 2.        ]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[      -inf 0.         0.69314718 1.09861229 1.38629436]


In [24]:
print (arr.max())
print (arr.sum())
print (arr.std())

4
10
1.4142135623730951


In [25]:
print(arr/arr)
print(1/arr)
print("")
print("0 divide by zero, nan")
print("1 divide by zero, inf")

[nan  1.  1.  1.  1.]
[       inf 1.         0.5        0.33333333 0.25      ]

0 divide by zero, nan
1 divide by zero, inf


# Pandas

## Series

A Series is very similar to a NumPy array. Only one columns. 

What differentiates the NumPy array from a Series, is that a Series can have axis labels, meaning it can be indexed by a label, instead of just a number location. It also doesn't need to hold numeric data, it can hold any arbitrary Python Object.

In [26]:
labels = ['a','b','c']
my_list = [10,20,30]
d = {'a':10,'b':20,'c':30}

In [27]:
# can be done for list and numpy array
pd.Series(data=my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [28]:
# # can be done for dictionaries
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [29]:
# series for string
pd.Series(data=labels)

0    a
1    b
2    c
dtype: object

In [30]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])  
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan']) 
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

## Dataframe

### Creating DataFrame

In [76]:
df = pd.DataFrame(np.random.randn(3,3),index='A B C'.split(),columns='W X Y'.split())
df

W         X         Y
A  0.245260 -0.391276  0.711289
B -0.615664 -0.072099 -0.545049
C  0.976406  2.046780  0.271006

In [77]:
print(type(df['W']))
df['W']

<class 'pandas.core.series.Series'>


A    0.245260
B   -0.615664
C    0.976406
Name: W, dtype: float64

In [78]:
print(type(df[['W','Y']]))
df[['W','Y']]

<class 'pandas.core.frame.DataFrame'>


W         Y
A  0.245260  0.711289
B -0.615664 -0.545049
C  0.976406  0.271006

In [79]:
# Creating New Column
df['new'] = df['W'] + df['Y']
df

W         X         Y       new
A  0.245260 -0.391276  0.711289  0.956549
B -0.615664 -0.072099 -0.545049 -1.160713
C  0.976406  2.046780  0.271006  1.247412

In [80]:
# set inplace = True else it will not execute permanently
df.drop('new',axis=1,inplace=True)
df

W         X         Y
A  0.245260 -0.391276  0.711289
B -0.615664 -0.072099 -0.545049
C  0.976406  2.046780  0.271006

In [81]:
# no inplace specified so it won't change the original dataframe
# axis = 0 to drop rows
df.drop('C',axis=0)

W         X         Y
A  0.245260 -0.391276  0.711289
B -0.615664 -0.072099 -0.545049

### DataFrame Selection

In [82]:
# selecting row
df.loc['A']

W    0.245260
X   -0.391276
Y    0.711289
Name: A, dtype: float64

In [83]:
# 2nd row and all columns
df.iloc[2,:]

W    0.976406
X    2.046780
Y    0.271006
Name: C, dtype: float64

In [84]:
# row and columns
df.loc['B','Y']

-0.5450486011113435

In [85]:
df.loc[['A','B'],['W','Y']]

W         Y
A  0.245260  0.711289
B -0.615664 -0.545049

In [86]:
df>0

W      X      Y
A   True  False   True
B  False  False  False
C   True   True   True

In [87]:
df[df>0]

W        X         Y
A  0.245260      NaN  0.711289
B       NaN      NaN       NaN
C  0.976406  2.04678  0.271006

In [88]:
df[df['W']>0]

W         X         Y
A  0.245260 -0.391276  0.711289
C  0.976406  2.046780  0.271006

In [89]:
df[df['W']>0][['Y','X']]

Y         X
A  0.711289 -0.391276
C  0.271006  2.046780

In [90]:
df[(df['W']>0) & (df['Y'] < 0)]

Empty DataFrame
Columns: [W, X, Y]
Index: []

In [91]:
# change value of single cell
df.at['A', 'W'] = 20
df

W         X         Y
A  20.000000 -0.391276  0.711289
B  -0.615664 -0.072099 -0.545049
C   0.976406  2.046780  0.271006

### DataFrame Index

In [92]:
df.reset_index()

index          W         X         Y
0     A  20.000000 -0.391276  0.711289
1     B  -0.615664 -0.072099 -0.545049
2     C   0.976406  2.046780  0.271006

In [93]:
df['States'] = 'CA NY WY'.split()
df

W         X         Y States
A  20.000000 -0.391276  0.711289     CA
B  -0.615664 -0.072099 -0.545049     NY
C   0.976406  2.046780  0.271006     WY

In [94]:
df.set_index('States',inplace=True)
df

W         X         Y
States                               
CA      20.000000 -0.391276  0.711289
NY      -0.615664 -0.072099 -0.545049
WY       0.976406  2.046780  0.271006

### Multi Index and Hierarchy

In [102]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
print(hier_index)
hier_index = pd.MultiIndex.from_tuples(hier_index)
print(hier_index)

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]
MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )


In [103]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

A         B
G1 1 -1.582278 -0.715042
   2 -0.133177 -1.006962
   3  0.364252  1.120753
G2 1 -0.988059 -0.163221
   2 -1.273703 -0.182859
   3  0.815169  2.258703

In [104]:
df.loc['G1']

A         B
1 -1.582278 -0.715042
2 -0.133177 -1.006962
3  0.364252  1.120753

In [105]:
df.loc['G1'].loc[1]

A   -1.582278
B   -0.715042
Name: 1, dtype: float64

In [106]:
df.index.names = ['Group','Num']
df

A         B
Group Num                    
G1    1   -1.582278 -0.715042
      2   -0.133177 -1.006962
      3    0.364252  1.120753
G2    1   -0.988059 -0.163221
      2   -1.273703 -0.182859
      3    0.815169  2.258703

In [115]:
# cross-section from the Series/DataFrame
df.loc['G1']

A         B
Num                    
1   -1.582278 -0.715042
2   -0.133177 -1.006962
3    0.364252  1.120753

In [113]:
df.xs(1,level='Num')

A         B
Group                    
G1    -1.582278 -0.715042
G2    -0.988059 -0.163221

## Missing Data

In [116]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [117]:
# rows
df.dropna(axis = 0)

A    B  C
0  1.0  5.0  1

In [118]:
# columns
df.dropna(axis=1)

C
0  1
1  2
2  3

In [119]:
# need to ahve at least 2 na
df.dropna(thresh=2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [120]:
# replace value
df.fillna(value='FILL VALUE')

A           B  C
0           1           5  1
1           2  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

## Groupby

In [121]:
# Create dataframe
df = pd.DataFrame({'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]})
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [122]:
df.groupby('Company').last()

Person  Sales
Company                
FB         Sarah    350
GOOG     Charlie    120
MSFT     Vanessa    124

In [123]:
df.groupby('Company').mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [124]:
df.groupby('Company').describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [125]:
df.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [126]:
df.groupby('Company').describe().transpose()['GOOG']

Sales  count      2.000000
       mean     160.000000
       std       56.568542
       min      120.000000
       25%      140.000000
       50%      160.000000
       75%      180.000000
       max      200.000000
Name: GOOG, dtype: float64

## DataFrame Combination

### Concating

In [128]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [129]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [130]:
pd.concat([df1,df2,df3],axis=1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

### Merging

In [131]:
# merge based on key
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})  

In [132]:
pd.merge(left,right,how='inner',on='key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [133]:
# merge based on 2 keys
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                      'key2': ['K0', 'K0', 'K0', 'K0'],
                       'C': ['C0', 'C1', 'C2', 'C3'],
                       'D': ['D0', 'D1', 'D2', 'D3']})

pd.merge(left, right, on=['key1', 'key2'])

key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [134]:
# outer will include everything
pd.merge(left, right, how='outer', on=['key1', 'key2'])

key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K1   A3   B3  NaN  NaN
5   K2   K0  NaN  NaN   C3   D3

In [135]:
# include everything on the right
pd.merge(left, right, how='right', on=['key1', 'key2'])

key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [136]:
# include everything on the left
pd.merge(left, right, how='left', on=['key1', 'key2'])

key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

### Joining

In [137]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [138]:
left.join(right)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [139]:
left.join(right, how='outer')

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

## DataFrame Operations

In [140]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [141]:
print(df.columns)
print(df.index)

Index(['col1', 'col2', 'col3'], dtype='object')
RangeIndex(start=0, stop=4, step=1)


In [142]:
df['col2'].unique()

array([444, 555, 666], dtype=int64)

In [143]:
df['col2'].nunique()

3

In [144]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [145]:
df.nunique()

col1    4
col2    3
col3    4
dtype: int64

In [146]:
def times2(x):
    return x*2

df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [147]:
# use lambda
df['col1'].apply(lambda x : x*2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [148]:
# permanently delete columns
del df['col1']
df

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [149]:
# sorting, inplace=False by default
df.sort_values(by='col2') 

col2 col3
0   444  abc
3   444  xyz
1   555  def
2   666  ghi

In [150]:
# check null values
df.isnull()

col2   col3
0  False  False
1  False  False
2  False  False
3  False  False

In [151]:
# pivot table
df = pd.DataFrame({
    'A':['foo','foo','foo','bar','bar','bar'],
    'B':['one','one','two','two','one','one'],
    'C':['x','y','x','y','x','y'],
    'D':[1,3,2,5,4,1]})
df

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [152]:
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

## Data Input and Output

In [153]:
pwd

'C:\\Users\\z0041yen\\Google Drive\\CS\\Data Science\\DS Python'

In [154]:
# read csv
df = pd.read_csv('./data/example.csv')
df.head()

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [155]:
# save csv
df.to_csv('./data/example',index=False)

In [159]:
# read csv
pd.read_excel('./data/Excel_Sample.xlsx',sheet_name='Sheet1').head()

Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [160]:
# save csv
df.to_excel('./data/Excel_Sample.xlsx',sheet_name='Sheet1')

In [161]:
# read html
df = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

## Pandas Exercise

In [162]:
sal = pd.read_csv('./data/Salaries.csv')
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [163]:
sal.describe() # 148654 Entries

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

In [164]:
sal['BasePay'].mean()

66325.44884050643

In [165]:
# What is the job title of JOSEPH DRISCOLL
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [166]:
# What is the name of highest paid person (including benefits)
sal.loc[sal['TotalPayBenefits'].idxmax()]

Id                                                               1
EmployeeName                                        NATHANIEL FORD
JobTitle            GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
BasePay                                                     167411
OvertimePay                                                      0
OtherPay                                                    400184
Benefits                                                       NaN
TotalPay                                                    567595
TotalPayBenefits                                            567595
Year                                                          2011
Notes                                                          NaN
Agency                                               San Francisco
Status                                                         NaN
Name: 0, dtype: object

In [167]:
# What was the average (mean) BasePay of all employees per year? (2011-2014) ? 
sal.groupby('Year').mean()['BasePay']

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

In [168]:
# What are the top 5 most common jobs?
sal['JobTitle'].value_counts().head(5)

Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: JobTitle, dtype: int64

In [169]:
# How many Job Titles were represented by only one person in 2013? (e.g. Job Titles with only one occurence in 2013?)
sum(sal[sal['Year']==2013]['JobTitle'].value_counts() == 1)

202

In [170]:
#  How many people have the word Chief in their job title?
sum(sal['JobTitle'].apply(lambda x: True if 'chief' in x.lower() else False))

627

In [171]:
# Is there a correlation between length of the Job Title string and Salary?
sal['title_len'] = sal['JobTitle'].apply(len)
sal[['title_len','TotalPayBenefits']].corr()

title_len  TotalPayBenefits
title_len          1.000000         -0.036878
TotalPayBenefits  -0.036878          1.000000

# End

In [172]:
end = datetime.now()
print(f"Total Time: {(end - start).total_seconds()} seconds ")

Total Time: 1978.771352 seconds 
